import { montage } from "../../test/interface";
import { act } from "react";
import { beforeEach, expect, it, vi } from "vitest";
import { CarteProfil } from "./CarteProfil";
import { useAppStore } from "../../stores/useAppStore";
vi.mock("../../i18n", () => ({ default: { t: (key: string) => key, changeLanguage: vi.fn() } }));
vi.mock("react-i18next", () => ({ useTranslation: () => ({ t: (key: string) => key }) }));
const quitter = vi.hoisted(() => vi.fn());
vi.mock("../../hooks/useVoiceChannel", () => ({ useVoiceChannel: () => ({ leaveVoiceChannel: quitter }), republishVoicePresence: vi.fn() }));
vi.mock("../../hooks/useLatence", () => ({ useLatence: () => null }));
vi.mock("./CarteReconnexion", () => ({ CarteReconnexion: () => null }));
vi.mock("../../services/lazyScreens", () => ({ preloadHeavyScreens: vi.fn() }));
vi.mock("../../services/voiceNativeService", () => ({ setVoiceNativeMuted: vi.fn(), setVoiceNativeDeafened: vi.fn() }));
vi.mock("../../services/voiceChannelSounds", () => ({ playMuteCue: vi.fn(), playUnmuteCue: vi.fn(), playDeafenCue: vi.fn(), playUndeafenCue: vi.fn() }));
vi.mock("../../services/matrixService", () => ({ publishLocalVoiceState: vi.fn() }));
const vue = montage();
beforeEach(() => { useAppStore.setState({ connectedVoiceChannel: null, isMuted: false, isDeafened: false, clockSkewMin: 0, e2eeUnhealthy: false }); quitter.mockClear(); });
it("raccrocher n'apparaît qu'en appel et quitte le bon salon", async () => {
  await vue.render(<CarteProfil compact={false} />);
  expect(vue.container.querySelector('[aria-label="voice.disconnect"]')).toBeNull();
  await act(async () => useAppStore.setState({ connectedVoiceChannel: "!salon" }));
  await vue.click('[aria-label="voice.disconnect"]');
  expect(quitter).toHaveBeenCalledWith("!salon");
});
it("micro et casque reflètent et basculent l'état", async () => {
  await vue.render(<CarteProfil compact={false} />);
  await vue.click('[aria-label="controls.mute"]');
  expect(useAppStore.getState().isMuted).toBe(true);
  expect(vue.container.querySelector('[aria-label="controls.unmute"]')?.getAttribute("aria-pressed")).toBe("true");
  await vue.click('[aria-label="controls.deafen"]');
  expect(useAppStore.getState().isDeafened).toBe(true);
});
it("en rail, micro et casque restent utilisables avec l'avatar et raccrocher", async () => {
  useAppStore.setState({ connectedVoiceChannel: "!salon" });
  await vue.render(<CarteProfil compact />);
  expect(vue.container.querySelector('[aria-label="settings.account"]')).not.toBeNull();
  expect(vue.container.querySelector('[aria-label="settings.title"]')).toBeNull();
  await vue.click('[aria-label="controls.mute"]');
  expect(useAppStore.getState().isMuted).toBe(true);
  expect(vue.container.querySelector('[aria-label="controls.unmute"]')?.getAttribute("aria-pressed")).toBe("true");
  await vue.click('[aria-label="controls.deafen"]');
  expect(useAppStore.getState().isDeafened).toBe(true);
  expect(vue.container.querySelector('[aria-label="controls.undeafen"]')?.getAttribute("aria-pressed")).toBe("true");
  await vue.click('[aria-label="voice.disconnect"]');
  expect(quitter).toHaveBeenCalledWith("!salon");
});
it("en rail hors appel, micro et casque restent accessibles sans raccrocher", async () => {
  await vue.render(<CarteProfil compact />);
  expect(vue.container.querySelector('[aria-label="controls.mute"]')).not.toBeNull();
  expect(vue.container.querySelector('[aria-label="controls.deafen"]')).not.toBeNull();
  expect(vue.container.querySelector('[aria-label="voice.disconnect"]')).toBeNull();
});
